spring:
  application:
    name: vote-webBack10005
server:
  port: 10005
url:
  sendToEncrytion: "http://127.0.0.1:10001/web-back/encode"
  receiveServer: "http://127.0.0.1:9999/server/vote"
  voteResults: "http://127.0.0.1:9999/server/result"